// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qknflbymwxfeyaspwhir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrbmZsYnltd3hmZXlhc3B3aGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjM4NDUsImV4cCI6MjA2OTE5OTg0NX0.T073EyCUV7y8B3FxxN3yDkRB9oWxMh00lK46B8QKU9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});